os:
  - linux
  - osx
osx_image: xcode9.2
dist: trusty
sudo: required
language: generic
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swiftenv; fi
install:
    - swiftenv install $(cat .swift-version)
script:
  - travis_wait swift build -c release
