os:
  - linux
  - osx
osx_image: xcode8.3
dist: trusty
sudo: required
language: generic
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - travis_wait swift build
  - travis_wait swift build -c release
